Gh 6
cdek-it/wordpress pull request #8
Opened 2024-05-31 09:29 UTC by DEMAxx

Please check.
Routes to core endpoint must to be changed. I`ll do it after confirm routes
Perhaps old links to edu end points will be change in future

2024-06-11 03:05 UTC, vermorag requested changes

2024-06-11 04:42 UTC, DEMAxx commented on src/Actions/Schedule/ReindexOrders.php
> +                $orderIndex = array_search($orderId, array_column($this->getTaskMeta(), 'external_id'));
имеешь в виду сразу присвоить OrderMetaData::updateMetaByOrderId uuid?

2024-06-11 04:44 UTC, DEMAxx commented on src/Contracts/TaskContract.php
> +    const FATAL_ERRORS = [500, 502, 503];
Добавить 504 или маску 5** ?

2024-06-11 04:46 UTC, DEMAxx commented on src/Exceptions/CdekCoreApiException.php
> +    protected bool $isSchedule = true;
Может класс переиминовать в CdekScheduleApiException или CdekScheduleException

2024-06-11 04:51 UTC, DEMAxx commented on src/CdekCoreApi.php
> +    public function sendTaskData($taskId, $data, array $headers = [])
2) Не совсем понимаю какую логику нужно переносить на этот уровень

2024-06-11 07:03 UTC, vermorag commented on src/Exceptions/CdekCoreApiException.php
> +    protected bool $isSchedule = true;
Дуамю, скорее уж `CdekSheduledTaskException` тогда.

2024-06-11 07:04 UTC, vermorag commented on src/Exceptions/CdekException.php
> +        protected bool $isSchedule = false;
Это не свойство всех эксепшенов. Управляй stopPropagation в более выкосоуровневом коде

2024-06-11 07:09 UTC, DEMAxx commented on src/CdekCoreApi.php
> +    public function sendTaskData($taskId, $data, array $headers = [])
Переписал

2024-06-11 07:21 UTC, DEMAxx commented on src/Actions/Schedule/CollectOrders.php
> +    public function __construct($taskId)
удалил конструктор из класса

2024-06-11 07:21 UTC, DEMAxx commented on src/Actions/Schedule/CollectOrders.php
> +    protected function reportOrders()
перенес в старт

2024-06-13 08:39 UTC, vermorag requested changes

2024-06-13 08:39 UTC, vermorag commented on src/CdekCoreApi.php
> +        return empty($this->status) || substr($this->status, 0, 1) == self::FATAL_ERRORS_FIRST_NUMBER;
str_starts_with

2024-06-13 08:39 UTC, vermorag commented on src/CdekCoreApi.php
> +            !in_array(
Лучше не использовать in_array.
Сделай три сравнения через или

2024-06-13 08:39 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    protected static array $taskData = [];
TaskMeta

2024-06-13 08:39 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    protected static array $taskData = [];
Задаче нужны только ее метаданные и ID

2024-06-13 08:39 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    protected static array $responseCursor = [];
Курсор задаче не нужен

2024-06-13 08:39 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    protected static array $errorCollection = [];
Не должно быть статичным

2024-06-13 08:39 UTC, vermorag commented on src/Contracts/TaskContract.php
> +        if(empty(self::$taskData[$this->taskId])){
Не может паралельно быть больше 1 задачи загружено в память

2024-06-13 08:39 UTC, vermorag commented on src/Contracts/TaskContract.php
> +        return self::$responseCursor[$this->taskId]['meta'];
Ты же курсор запрашиваешь?

2024-06-13 08:39 UTC, vermorag commented on src/Exceptions/CdekScheduledTaskException.php
> +        string $message = '',
Почему? Если месседж обязательный, то зачем его делать пустой строкой?

2024-06-13 08:39 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +    private static string $tokenAdmin = '';
Почему токен может быть пустой строке равен? Если его нет, то лучше null

2024-06-13 08:39 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +        return static::$apiUrlString = $this->getEndPointFromToken($this->getToken());
А почему бы тут тогда не записать в кэш, чтобы в нем были данные?

2024-06-13 08:39 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +        return static::$apiUrlString = $this->getEndPointFromToken($this->getToken());
Проблема N+1

2024-06-13 08:39 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +    private function getTokenFromSettings(): ?string
Ты же из кэша получаешь, а не из настроек

2024-06-13 08:39 UTC, vermorag commented on src/Managers/TaskManager.php
> +        self::class,
Что произойдет, если ядро отправит задачу с именем, который равен `Config::TASK_MANAGER_HOOK_NAME`?

2024-06-13 08:39 UTC, vermorag commented on src/Managers/TaskManager.php
> +        if (empty($response['cursor'])) {
Ты проверяешь только наличие курсора, а надо еще его содержимое (вложенные в объект ключи)

2024-06-13 08:39 UTC, vermorag commented on src/Uninstaller.php
> +        FileCache::clear();
Зачем сбрасывать файловый кэш? Надо сбрасывать кэш токена API2, а не ядра

2024-06-13 08:39 UTC, vermorag commented on src/Contracts/TaskContract.php
> +            self::$errorCollection[$this->taskId][] = __('Request to api was failed', 'cdekdelivery');
esch_html__

2024-06-14 02:36 UTC, vermorag requested changes

2024-06-14 02:36 UTC, vermorag commented on src/Actions/Schedule/CollectOrders.php
> +                            $result->orders
```suggestion
                            $result->orders,
```

2024-06-14 02:36 UTC, vermorag commented on src/Actions/Schedule/ReindexOrders.php
>          public function start()
```suggestion
        public function start(): void
```

2024-06-14 02:36 UTC, vermorag commented on src/Cache/FileCache.php
> +    public static function putVars($vars): void
Типизация

2024-06-14 02:36 UTC, vermorag commented on src/Cache/FileCache.php
>                  throw new CdekApiException('[CDEKDelivery] Failed check directory rights',
Тут то у тебя не прошла проверка не на директорию, а на файл

2024-06-14 02:36 UTC, vermorag commented on src/Cache/FileCache.php
> +     * @return void
Зачем дублировать? У тебя в коде уже есть тип возвращаемого значения.

2024-06-14 02:36 UTC, vermorag commented on src/CdekCoreApi.php
> +    public function taskInfo($taskId, TaskOutputData $data)
```suggestion
    public function taskInfo(string $taskId, TaskOutputData $data)
```

2024-06-14 02:36 UTC, vermorag commented on src/CdekCoreApi.php
> +    public function sendTaskData($taskId, TaskOutputData $data)
```suggestion
    public function sendTaskData(string $taskId, TaskOutputData $data)
```

2024-06-14 02:36 UTC, vermorag commented on src/CdekCoreApi.php
> +     * @return mixed|string
Почему mixed?

2024-06-14 02:36 UTC, vermorag commented on src/CdekCoreApi.php
> +    private function initData($response): array
Типизация

2024-06-14 02:36 UTC, vermorag commented on src/Contracts/TaskContract.php
> +     * @return array
Давай не дублировать информацию

2024-06-14 02:36 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    protected function initData($response): void
Типизация

2024-06-14 02:36 UTC, vermorag commented on src/Managers/TaskManager.php
>      public function __construct($taskId)
```suggestion
    public function __construct(string $taskId)
```

2024-06-14 02:36 UTC, vermorag commented on src/Managers/TaskManager.php
> +     * @return void
Давай не дублировать

2024-06-14 02:36 UTC, vermorag commented on src/CdekCoreApi.php
> +     * @return array
Давай не дублировать

2024-06-14 02:36 UTC, vermorag commented on src/CdekCoreApi.php
> +    public function taskManager($data = null)
Типизация

2024-06-14 02:36 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    public static function init($taskId = 'task_manager'): void
```suggestion
    public static function init(string $taskId = 'task_manager'): void
```

2024-06-14 02:36 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    public static function init($taskId = 'task_manager'): void
И почему вообще это ID, а не Name?
ID же - это uuid?

2024-06-14 02:36 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +     * @return string
Давай не дублировать информацию

2024-06-14 02:36 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +     * @return mixed|string
Почему mixed?

2024-06-14 02:36 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +     * @return string
Давай не дублировать информацию

2024-06-14 02:36 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +     * @return array
Давай не дублировать информацию

2024-06-14 02:36 UTC, vermorag commented on src/Model/TaskData.php
> +    public function __construct($requestData)
```suggestion
    public function __construct(array $requestData)
```

2024-06-14 02:36 UTC, vermorag commented on src/Model/TaskData.php
> +     * @return mixed
Почему mixed?

2024-06-14 02:36 UTC, vermorag commented on src/Model/TaskData.php
> +     * @return mixed
Почему mixed?

2024-06-14 02:36 UTC, vermorag commented on src/Model/TaskData.php
> +     * @return mixed
Почему mixed?

2024-06-14 02:36 UTC, vermorag commented on src/Model/TaskData.php
> +    public function isScheduleTask()
```suggestion
    public function isScheduledTask()
```

2024-06-14 02:36 UTC, vermorag commented on src/Model/TaskOutputData.php
> +        ?string $status,
Это единственное поле, которое обязательно во всех случаях для бэкенда. А ты его делаешь Nullable. Возмжоно, стоит его и для DTO сделать обязательным, чтобы нельзя было создать ответ серверу без информации о статусе

2024-06-17 03:51 UTC, vermorag requested changes

2024-06-17 03:51 UTC, vermorag commented on src/Actions/Schedule/CollectOrders.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Cache/FileCache.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Cache/FileCache.php
> +        if(empty($vars)){
```suggestion
        if($vars === null){
```

Такая проверка в данном случае экономичнее

2024-06-17 03:51 UTC, vermorag commented on src/Contracts/TaskContract.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Contracts/TaskContract.php
> +    public static function init($taskId): void
```suggestion
    public static function init(string $taskId): void
```

2024-06-17 03:51 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +    public function getPath(): string
```suggestion
    public function getOrRefreshApiPath(): string
```

2024-06-17 03:51 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +    private function getEndPointFromToken($token)
```suggestion
    private function getEndPointFromToken(string $token): ?string
```

2024-06-17 03:51 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +        return json_decode(base64_decode($arToken[count($arToken) - 1]), true)['endpoint'];
```suggestion
        return json_decode(base64_decode($arToken[count($arToken) - 1]), true)['endpoint'] ?? null;
```

2024-06-17 03:51 UTC, vermorag commented on src/Helpers/DBCoreTokenStorage.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Exceptions/CdekScheduledTaskException.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Managers/TaskManager.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Managers/TaskManager.php
> +        }
```suggestion
        foreach (self::TASK_CLASSES as $arTaskClass) {
            $task = new TaskContract();

            if (!($task instanceof TaskContract)) {
                continue;
            }

            $task::registerAction();
        }
```

2024-06-17 03:51 UTC, vermorag commented on src/Managers/TaskManager.php
> +            static fn($class) =>
Почему на [src/Managers/TaskManager.php:67](https://github.com/cdek-it/wordpress/pull/8/files#diff-7dc55e9c530a3375f7731cb9a03cb07d3c4fd179dbf4add904dd9db2a5ca83b0R67) ты делаешь проверку, а тут нет?

2024-06-17 03:51 UTC, vermorag commented on src/Managers/TaskManager.php
> +        $dateTime = new \DateTime('now + 1 hour');
Use import, please

2024-06-17 03:51 UTC, vermorag commented on src/Managers/TaskManager.php
> +                static fn($class) => $class::getName(),
Почему на [src/Managers/TaskManager.php:67](https://github.com/cdek-it/wordpress/pull/8/files#diff-7dc55e9c530a3375f7731cb9a03cb07d3c4fd179dbf4add904dd9db2a5ca83b0R67) ты делаешь проверку, а тут нет?

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +    public function createTaskWork()
```suggestion
    public function createTaskWork(): void
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +    private $name;
```suggestion
    private string $name;
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +    private $name;
```suggestion
    private string $name;
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +    private $id;
```suggestion
    private string $id;
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +    private $schedule;
```suggestion
    private ?string $schedule;
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +        return !empty($this->schedule);
```suggestion
        return $this->schedule !== null;
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskData.php
> +    public function getSchedule(): string
```suggestion
    public function getSchedule(): ?string
```

2024-06-17 03:51 UTC, vermorag commented on src/Model/TaskOutputData.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 03:51 UTC, vermorag commented on src/Uninstaller.php
> +
```suggestion
namespace {

    defined('ABSPATH') or exit;
}
```

2024-06-17 08:49 UTC, vermorag requested changes

2024-06-17 08:49 UTC, vermorag commented on src/Actions/Schedule/CollectOrders.php
> +        const ORDERS_LIMIT = 10000;
```suggestion
        private const ORDERS_LIMIT = 10000;
```

2024-06-17 08:49 UTC, vermorag commented on src/Cache/FileCache.php
> +        const CACHE_FILE_NAME = '.cache.php';
```suggestion
        private const CACHE_FILE_NAME = '.cache.php';
```

2024-06-18 02:20 UTC, vermorag approved these changes

2024-06-18 10:06 UTC, merged